name: Download bilibili Emotes

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 0 * * *"
  watch:
    types: [started]
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python # install python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests # install requests
      run: |
        pip install requests
        pip install tqdm
    - name: Download
      run: | 
        python3 Download.py ${{ secrets.SESSDATA }}
        cat log.log
        rm log.log
    - name: Commit # update log to Github
      run: |
        git config --global user.email GamerNoTitle@outlook.com
        git config --global user.name GamerNoTitle
        git add .
        git commit -m "New emotes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
